import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Itaú - Giulia Trevisan",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",        
    shortcut: "/logo.svg",   
    apple: "/logo.svg",      
    },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${lato.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
